### ISSUE TITLE
Missing from Firefox marketplace?

### ISSUE THREAD

**Issue by jordemort** [K-Francis-H/libretranslate-unofficial-ff-extension#1]
It looks like this addon was once available via addons.mozilla.org, but it no longer appears to be there. What happened?

**Comment by K-Francis-H** [comment]
Thanks for letting me know, I changed the add-on name to not have LibreTranslate in it and that changed the add-on store link, but I never updated it here. I've fixed the README. Here's the correct link: [https://addons.mozilla.org/en-US/firefox/addon/open-translate-addon/](https://addons.mozilla.org/en-US/firefox/addon/open-translate-addon/)
